version: '3.8'

services:
  api:
    container_name: api
    build: .
    environment:
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - PG_DB=${PG_DB}
      - PG_USER=${PG_USER}
      - PG_PASS=${PG_PASS}
    ports:
      - ${API_PORT}:8000
    volumes:
      - .:/app
    # command: ["/app/wait-for-it.sh", "postgres_db:5432", "--", "/app/entrypoint.sh"]
    # command: ["tail", "-f", "/dev/null"]
    command: ["bash", "entrypoint.sh"]
    # command: ""
  postgres_db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
    ports:
      - ${PG_PORT}:5432
    volumes:
      # - postgres-data:/var/lib/postgresql/data
      - ./postgres/init_data:/init_data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c work_mem=1GB -c maintenance_work_mem=1GB -c max_wal_size=4GB

