version: '3.8'

services:
  web:
    build: .
    environment:
      - PG_HOST=postgres.lab.karpov.courses
      - PG_PORT=6432
      - PG_DATABASE=startml
      - PG_USER=robot-startml-ro
      - PG_PASS=pheiph0hahj1Vaif
    ports:
      - "8000:8000"
    command: sh -c "uvicorn app:app --reload --port=8000 --host=0.0.0.0"
    # command: ["tail", "-f", "dev/null"]
  postgres_db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
