version: '3.8'

services:
  api:
    container_name: api
    build: .
    environment:
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - PG_DB=${PG_DB}
      - PG_USER=${PG_USER}
      - PG_PASS=${PG_PASS}
    ports:
      - ${API_PORT}:8000
    volumes:
      - .:/app
    command: ["bash", "api_entrypoint.sh"]
  postgres_db:
    container_name: postgres
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
    ports:
      - ${PG_PORT}:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/scripts:/docker-entrypoint-initdb.d/
    command: ["postgres", "-c", "work_mem=1GB", "-c", "maintenance_work_mem=1GB", "-c", "max_wal_size=4GB"]


volumes:
  postgres-data: